on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build firmware
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install platformio
        run: pip install platformio==5.2.4

      - name: build
        run: pio run
